 --CREATE DATABASE MVCSHOP;
 --GO
 --USE MVCSHOP;
 --GO

 --CREATE DATABASE TEST;
 --GO
 --USE TEST;
 --GO
 --DROP DATABASE MVCSHOP;
 --GO



--Функция замены NULL на 0
CREATE FUNCTION ReplaceNullToZero (@VALUE DECIMAL)
RETURNS DECIMAL
-- EXECUTE AS CALLER значит что права на выполнение функции имеет тот кто ее вызывает
WITH EXECUTE AS CALLER
AS
BEGIN 
	DECLARE @CHANGEDVALUE DECIMAL;
	     IF(@VALUE = NULL)
		   SET @CHANGEDVALUE = 0;
	   ELSE 
	       SET @CHANGEDVALUE = @VALUE;
	RETURN (@CHANGEDVALUE);
	  END;
GO



-- Заказчик
	CREATE TABLE CUSTOMERS
	(
		ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID() NOT NULL,
	  NAME VARCHAR NOT NULL,
	  CODE VARCHAR COLLATE Cyrillic_General_BIN NOT NULL
	 CHECK ([CODE] LIKE REPLACE('XXXX-XXXX','X','[0123456789]') AND ISDATE(RIGHT([CODE],4))=1),
   ADDRESS VARCHAR,
  DISCOUNT DECIMAL(18,2) DEFAULT(0),
	);
	GO
	


	CREATE TABLE ORDERS
	(
    	   ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID() NOT NULL,
  CUSTOMER_ID UNIQUEIDENTIFIER REFERENCES CUSTOMERS(ID) NOT NULL,
   ORDER_DATE DATE NOT NULL,
SHIPMENT_DATE DATE,
 ORDER_NUMBER INT,
       STATUS VARCHAR,
  	);
	GO

	CREATE TABLE ITEMS
	(
		ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID() NOT NULL,
	  CODE VARCHAR COLLATE Cyrillic_General_BIN NOT NULL
	 CHECK ([CODE] LIKE REPLACE(REPLACE('XX-XXXX-YYXX','X','[0123456789]'),'Y','[ABCDEFGHIJKLMNOPQRSTUVWXYZ]')),
	  NAME VARCHAR,
     PRICE DECIMAL(18,2),
  CATEGORY VARCHAR(30)
	);
	GO

	CREATE TABLE ORDER_ITEM
	(
	     ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID() NOT NULL,
   ORDER_ID UNIQUEIDENTIFIER REFERENCES ORDERS(ID) NOT NULL,
    ITEM_ID UNIQUEIDENTIFIER REFERENCES ITEMS(ID) NOT NULL,
ITEMS_COUNT INT NOT NULL,
 ITEM_PRICE DECIMAL NOT NULL,
	);
	GO




