//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathWindowsServiceHost.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBasicMath")]
    public interface IBasicMath {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicMath/Add", ReplyAction="http://tempuri.org/IBasicMath/AddResponse")]
        int Add(int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicMath/Add", ReplyAction="http://tempuri.org/IBasicMath/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(int X, int Y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBasicMathChannel : MathWindowsServiceHost.ServiceReference1.IBasicMath, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BasicMathClient : System.ServiceModel.ClientBase<MathWindowsServiceHost.ServiceReference1.IBasicMath>, MathWindowsServiceHost.ServiceReference1.IBasicMath {
        
        public BasicMathClient() {
        }
        
        public BasicMathClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BasicMathClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicMathClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicMathClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int X, int Y) {
            return base.Channel.Add(X, Y);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int X, int Y) {
            return base.Channel.AddAsync(X, Y);
        }
    }
}
